var stIsIE=!1;
sorttable={init:function(){if(!arguments.callee.done&&(arguments.callee.done=!0,_timer&&clearInterval(_timer),document.createElement&&document.getElementsByTagName))sorttable.DATE_RE=/^(\d\d?)[\/\.-](\d\d?)[\/\.-]((\d\d)?\d\d)$/,forEach(document.getElementsByTagName("table"),function(a){a.className.search(/\bsortable\b/)!=-1&&sorttable.makeSortable(a)})},makeSortable:function(a){a.getElementsByTagName("thead").length==0&&(the=document.createElement("thead"),the.appendChild(a.rows[0]),a.insertBefore(the,
a.firstChild));if(a.tHead==null)a.tHead=a.getElementsByTagName("thead")[0];if(a.tHead.rows.length==1){sortbottomrows=[];for(var b=0;b<a.rows.length;b++)a.rows[b].className.search(/\bsortbottom\b/)!=-1&&(sortbottomrows[sortbottomrows.length]=a.rows[b]);if(sortbottomrows){a.tFoot==null&&(tfo=document.createElement("tfoot"),a.appendChild(tfo));for(b=0;b<sortbottomrows.length;b++)tfo.appendChild(sortbottomrows[b]);delete sortbottomrows}headrow=a.tHead.rows[0].cells;for(b=0;b<headrow.length;b++)if(!headrow[b].className.match(/\bsorttable_nosort\b/))(mtch=
headrow[b].className.match(/\bsorttable_([a-z0-9]+)\b/))&&(override=mtch[1]),headrow[b].sorttable_sortfunction=mtch&&typeof sorttable["sort_"+override]=="function"?sorttable["sort_"+override]:sorttable.guessType(a,b),headrow[b].sorttable_columnindex=b,headrow[b].sorttable_tbody=a.tBodies[0],dean_addEvent(headrow[b],"click",function(){if(this.className.search(/\bsorttable_sorted\b/)!=-1)sorttable.reverse(this.sorttable_tbody),this.className=this.className.replace("sorttable_sorted","sorttable_sorted_reverse"),
this.removeChild(document.getElementById("sorttable_sortfwdind")),sortrevind=document.createElement("span"),sortrevind.id="sorttable_sortrevind",sortrevind.innerHTML=stIsIE?'&nbsp<font face="webdings">5</font>':"&nbsp;&#x25B4;",this.appendChild(sortrevind);else if(this.className.search(/\bsorttable_sorted_reverse\b/)!=-1)sorttable.reverse(this.sorttable_tbody),this.className=this.className.replace("sorttable_sorted_reverse","sorttable_sorted"),this.removeChild(document.getElementById("sorttable_sortrevind")),
sortfwdind=document.createElement("span"),sortfwdind.id="sorttable_sortfwdind",sortfwdind.innerHTML=stIsIE?'&nbsp<font face="webdings">6</font>':"&nbsp;&#x25BE;",this.appendChild(sortfwdind);else{theadrow=this.parentNode;forEach(theadrow.childNodes,function(a){if(a.nodeType==1)a.className=a.className.replace("sorttable_sorted_reverse",""),a.className=a.className.replace("sorttable_sorted","")});(sortfwdind=document.getElementById("sorttable_sortfwdind"))&&sortfwdind.parentNode.removeChild(sortfwdind);
(sortrevind=document.getElementById("sorttable_sortrevind"))&&sortrevind.parentNode.removeChild(sortrevind);this.className+=" sorttable_sorted";sortfwdind=document.createElement("span");sortfwdind.id="sorttable_sortfwdind";sortfwdind.innerHTML=stIsIE?'&nbsp<font face="webdings">6</font>':"&nbsp;&#x25BE;";this.appendChild(sortfwdind);row_array=[];col=this.sorttable_columnindex;rows=this.sorttable_tbody.rows;for(var a=0;a<rows.length;a++)row_array[row_array.length]=[sorttable.getInnerText(rows[a].cells[col]),
rows[a]];row_array.sort(this.sorttable_sortfunction);tb=this.sorttable_tbody;for(a=0;a<row_array.length;a++)tb.appendChild(row_array[a][1]);delete row_array}})}},guessType:function(a,b){sortfn=sorttable.sort_alpha;for(var c=0;c<a.tBodies[0].rows.length;c++)if(text=sorttable.getInnerText(a.tBodies[0].rows[c].cells[b]),text!=""){if(text.match(/^-?[\ufffd$\ufffd]?[\d,.]+%?$/))return sorttable.sort_numeric;if(possdate=text.match(sorttable.DATE_RE))if(first=parseInt(possdate[1]),second=parseInt(possdate[2]),
first>12)return sorttable.sort_ddmm;else if(second>12)return sorttable.sort_mmdd;else sortfn=sorttable.sort_ddmm}return sortfn},getInnerText:function(a){hasInputs=typeof a.getElementsByTagName=="function"&&a.getElementsByTagName("input").length;if(a.getAttribute("sorttable_customkey")!=null)return a.getAttribute("sorttable_customkey");else if(typeof a.textContent!="undefined"&&!hasInputs)return a.textContent.replace(/^\s+|\s+$/g,"");else if(typeof a.innerText!="undefined"&&!hasInputs)return a.innerText.replace(/^\s+|\s+$/g,
"");else if(typeof a.text!="undefined"&&!hasInputs)return a.text.replace(/^\s+|\s+$/g,"");else switch(a.nodeType){case 3:if(a.nodeName.toLowerCase()=="input")return a.value.replace(/^\s+|\s+$/g,"");case 4:return a.nodeValue.replace(/^\s+|\s+$/g,"");case 1:case 11:for(var b="",c=0;c<a.childNodes.length;c++)b+=sorttable.getInnerText(a.childNodes[c]);return b.replace(/^\s+|\s+$/g,"");default:return""}},reverse:function(a){newrows=[];for(var b=0;b<a.rows.length;b++)newrows[newrows.length]=a.rows[b];for(b=
newrows.length-1;b>=0;b--)a.appendChild(newrows[b]);delete newrows},sort_numeric:function(a,b){aa=parseFloat(a[0].replace(/[^0-9.-]/g,""));isNaN(aa)&&(aa=0);bb=parseFloat(b[0].replace(/[^0-9.-]/g,""));isNaN(bb)&&(bb=0);return aa-bb},sort_alpha:function(a,b){return a[0]==b[0]?0:a[0]<b[0]?-1:1},sort_ddmm:function(a,b){mtch=a[0].match(sorttable.DATE_RE);y=mtch[3];m=mtch[2];d=mtch[1];m.length==1&&(m="0"+m);d.length==1&&(d="0"+d);dt1=y+m+d;mtch=b[0].match(sorttable.DATE_RE);y=mtch[3];m=mtch[2];d=mtch[1];
m.length==1&&(m="0"+m);d.length==1&&(d="0"+d);dt2=y+m+d;return dt1==dt2?0:dt1<dt2?-1:1},sort_mmdd:function(a,b){mtch=a[0].match(sorttable.DATE_RE);y=mtch[3];d=mtch[2];m=mtch[1];m.length==1&&(m="0"+m);d.length==1&&(d="0"+d);dt1=y+m+d;mtch=b[0].match(sorttable.DATE_RE);y=mtch[3];d=mtch[2];m=mtch[1];m.length==1&&(m="0"+m);d.length==1&&(d="0"+d);dt2=y+m+d;return dt1==dt2?0:dt1<dt2?-1:1},shaker_sort:function(a,b){for(var c=0,e=a.length-1,g=!0;g;){for(var g=!1,f=c;f<e;++f)b(a[f],a[f+1])>0&&(g=a[f],a[f]=
a[f+1],a[f+1]=g,g=!0);e--;if(!g)break;for(f=e;f>c;--f)b(a[f],a[f-1])<0&&(g=a[f],a[f]=a[f-1],a[f-1]=g,g=!0);c++}}};document.addEventListener&&document.addEventListener("DOMContentLoaded",sorttable.init,!1);if(/WebKit/i.test(navigator.userAgent))var _timer=setInterval(function(){/loaded|complete/.test(document.readyState)&&sorttable.init()},10);window.onload=sorttable.init;
function dean_addEvent(a,b,c){if(a.addEventListener)a.addEventListener(b,c,!1);else{if(!c.$$guid)c.$$guid=dean_addEvent.guid++;if(!a.events)a.events={};var e=a.events[b];e||(e=a.events[b]={},a["on"+b]&&(e[0]=a["on"+b]));e[c.$$guid]=c;a["on"+b]=handleEvent}}dean_addEvent.guid=1;function removeEvent(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.events&&a.events[b]&&delete a.events[b][c.$$guid]}
function handleEvent(a){var b=!0,a=a||fixEvent(((this.ownerDocument||this.document||this).parentWindow||window).event),c=this.events[a.type],e;for(e in c)this.$$handleEvent=c[e],this.$$handleEvent(a)===!1&&(b=!1);return b}function fixEvent(a){a.preventDefault=fixEvent.preventDefault;a.stopPropagation=fixEvent.stopPropagation;return a}fixEvent.preventDefault=function(){this.returnValue=!1};fixEvent.stopPropagation=function(){this.cancelBubble=!0};
if(!Array.forEach)Array.forEach=function(a,b,c){for(var e=0;e<a.length;e++)b.call(c,a[e],e,a)};Function.prototype.forEach=function(a,b,c){for(var e in a)typeof this.prototype[e]=="undefined"&&b.call(c,a[e],e,a)};String.forEach=function(a,b,c){Array.forEach(a.split(""),function(e,g){b.call(c,e,g,a)})};
var forEach=function(a,b,c){if(a){var e=Object;if(a instanceof Function)e=Function;else if(a.forEach instanceof Function){a.forEach(b,c);return}else typeof a=="string"?e=String:typeof a.length=="number"&&(e=Array);e.forEach(a,b,c)}};