var plot=[],itin_table=[],plot_t_highlight=[NaN,NaN],viewer_Traj_ID=-1,SCdist=[],animation={},rotation={};function TrajViewer_NA(){alert("Trajectory not available yet.")}
function TrajViewer_open(b){var a=document.getElementById("trajdiv");viewer_Traj_ID=b;idx_trajs=trajs["id"+b];a.style.display="inline";var c=window.innerHeight||window.document.documentElement.clientHeight||window.document.body.clientHeight,g=typeof window.innerWidth=="number"?window.pageYOffset:document.documentElement.scrollTop;document.getElementById("tv_nexttraj").style.visibility="visible";document.getElementById("tv_prevtraj").style.visibility="visible";row_idx=document.getElementById("tr_"+b).rowIndex;if(row_idx==1)document.getElementById("tv_prevtraj").style.visibility="hidden";if(row_idx==document.getElementById("results_table").rows.length-1)document.getElementById("tv_nexttraj").style.visibility="hidden";computeTraj(idx_trajs);
setupStats(idx_trajs);plotBuffer()}function TrajViewer_close(){document.getElementById("trajdiv").style.display="none"}function TrajViewer_next(b){b=document.getElementById("tr_"+viewer_Traj_ID).rowIndex+b;Traj_ID=document.getElementById("results_table").rows[b].id.substr(3);animate_pause();TrajViewer_open(Traj_ID)}var PLOT_CTR=0,PLOT_NODE=1,PLOT_SC=2,PLOT_ARROW=3;
function computeTraj(b){var a=0,c=0,g,d=0,f=[],d=[],e=[],j;ctrID=10;prtID=0;plot=[];plot[PLOT_CTR]={};plot[PLOT_CTR].ID=ctrID;plot[PLOT_CTR].color=getObjectColor(ctrID);plot[PLOT_CTR].flag="*";plot[PLOT_CTR].t=[NaN];plot[PLOT_CTR].RX=[0];plot[PLOT_CTR].RY=[0];plot[PLOT_CTR].RZ=[0];plot[PLOT_NODE]={};plot[PLOT_NODE].ID=-1;plot[PLOT_NODE].color=getObjectColor(plot[PLOT_NODE].ID);plot[PLOT_NODE].flag="x";plot[PLOT_NODE].t=[];plot[PLOT_NODE].RX=[];plot[PLOT_NODE].RY=[];plot[PLOT_NODE].RZ=[];plot[PLOT_SC]=
{};plot[PLOT_SC].ID=-1;plot[PLOT_SC].color=getObjectColor(plot[PLOT_SC].ID);plot[PLOT_SC].flag="-";plot[PLOT_SC].t=[];plot[PLOT_SC].RX=[];plot[PLOT_SC].RY=[];plot[PLOT_SC].RZ=[];plot[PLOT_ARROW]={};plot[PLOT_ARROW].ID=-1;plot[PLOT_ARROW].color=getObjectColor(plot[PLOT_ARROW].ID);plot[PLOT_ARROW].flag=">";plot[PLOT_ARROW].RX=[];plot[PLOT_ARROW].RY=[];plot[PLOT_ARROW].RZ=[];plot[PLOT_ARROW].VX=[];plot[PLOT_ARROW].VY=[];plot[PLOT_ARROW].VZ=[];plot[PLOT_ARROW].t=[];SCdist=[];SCdist.sun=[];SCdist.sun.min=
Infinity;SCdist.sun.max=0;SCdist.earth=[];SCdist.earth.min=Infinity;SCdist.earth.max=0;b=segs["id"+trajs.Traj_ID[b]];for(a=b[0];a<b[1];a++)if(d=segs.T[a+1]-segs.T[a],!(d<60)){j=getGM(segs.SPK_ID[a]);c=segs.T[a];t_mid=segs.T[a]+0.5*d;for(arrow_drawn=d<1*o.day||segs.SPK_ID[a]!=ID_SUN;;){e=segs.nodes[a]!=NODE_STAY_ARRIVAL?Prop2B(j,[segs.RX[a],segs.RY[a],segs.RZ[a],segs.VX[a],segs.VY[a],segs.VZ[a]],c-segs.T[a]):[0,0,0,0,0,0];d=PropNaturalBody(segs.SPK_ID[a],ctrID,c);for(g=0;g<6;g++)f[g]=e[g]+d[g];pushPosToBuffer(PLOT_SC,
c,f);c==segs.T[a]&&segs.nodes[a]!=0&&pushPosToBuffer(PLOT_NODE,c,f);c==segs.T[a+1]&&segs.nodes[a+1]!=0&&pushPosToBuffer(PLOT_NODE,c,f);!arrow_drawn&&c>t_mid&&(pushStateToBuffer(PLOT_ARROW,c,f),arrow_drawn=1);r=norm3(f);SCdist.sun.min=Math.min(r,SCdist.sun.min);SCdist.sun.max=Math.max(r,SCdist.sun.max);d=PropNaturalBody(segs.SPK_ID[a],ID_EARTH,c);for(g=0;g<6;g++)f[g]=e[g]+d[g];r=norm3(f);SCdist.earth.min=Math.min(r,SCdist.earth.min);SCdist.earth.max=Math.max(r,SCdist.earth.max);if(c==segs.T[a+1])break;
c+=432E3;c=c>segs.T[a+1]?segs.T[a+1]:c}}for(a=b[0];a<=b[1];a++){for(d=0;d<plot.length&&plot[d].ID!=segs.SPK_ID[a];)d++;if(d==plot.length){d=plot.length;plot[d]={};plot[d].ID=segs.SPK_ID[a];plot[d].color=getObjectColor(segs.SPK_ID[a]);plot[d].flag="-";plot[d].t=[];plot[d].RX=[];plot[d].RY=[];plot[d].RZ=[];T=Body_period(segs.SPK_ID[a]);c=segs.T[b[0]]-T*0.1;t_end=Math.max(segs.T[b[1]]+T*0.2,c+T*1.1);dnu=5*o.DEG2RAD;f=PropNaturalBody(segs.SPK_ID[a],ctrID,c);for(h=norm3(cross3([f[0],f[1],f[2]],[f[3],f[4],
f[5]]));c<=t_end;)f=PropNaturalBody(segs.SPK_ID[a],ctrID,c),pushPosToBuffer(d,c,f),c+=Math.min(T/50,sq(norm3([f[0],f[1],f[2]]))*dnu/h)}}animate_pause();document.getElementById("btn_pause").style.display="none";document.getElementById("btn_play").style.display="inline";animation.tstart=segs.T[b[0]];animation.tend=segs.T[b[1]];animation.t=animation.tstart;animation.tstep=Math.max((animation.tend-animation.tstart)/500,86400);animation.on=1;animation.timer=0;rotation.mousedown=0;rotation.xy_mousedown=
[0,0];rotation.x_axis=[0,1,0];rotation.y_axis=[1,0,0];rotation.g=[[1,0,0],[0,1,0],[0,0,1]];rotation.g_base=[[1,0,0],[0,1,0],[0,0,1]];a=document.getElementById("tv_canvas");a.addEventListener("mousedown",rotation_mousedown,!1);a.addEventListener("mousemove",rotation_mousemove,!1);a.addEventListener("mouseup",rotation_mouseup,!1);a.addEventListener("dblclick",rotation_dblclick,!1)}function pushPosToBuffer(b,a,c){plot[b].t.push(a);plot[b].RX.push(c[0]);plot[b].RY.push(c[1]);plot[b].RZ.push(c[2])}
function pushStateToBuffer(b,a,c){pushPosToBuffer(b,a,c);plot[b].VX.push(c[3]);plot[b].VY.push(c[4]);plot[b].VZ.push(c[5])}
function plotBuffer(){var b,a,c,g;c=[];var d=[],f=[];g=document.getElementById("tv_canvas");var e=g.getContext("2d");e.fillStyle="#000000";e.fillRect(0,0,g.width,g.height);c[0]=0;c[1]=0;c[2]=0;for(b=c[3]=0;b<plot.length;b++)for(a=0;a<plot[b].RX.length;a+=5)xy=m_x_v3(rotation.g,[plot[b].RX[a],plot[b].RY[a],plot[b].RZ[a]]),c[0]=Math.min(c[0],xy[0]),c[1]=Math.max(c[1],xy[0]),c[2]=Math.min(c[2],xy[1]),c[3]=Math.max(c[3],xy[1]);d[0]=-c[0]/(c[1]-c[0])*g.width*0.95+0.025*g.width;d[1]=(g.height+c[2]/(c[3]-
c[2])*g.height)*0.95+0.025*g.height;f[0]=0.95*Math.min(g.width/(c[1]-c[0]),g.height/(c[3]-c[2]));f[1]=-f[0];for(b=plot.length-1;b>=0;b--)if(plot[b].flag=="*"){e.beginPath();xy=get_xy([plot[b].RX[0],plot[b].RY[0],plot[b].RZ[0]],f,d,rotation.g);e.lineWidth=2;for(a=0;a<8;a++)e.moveTo(xy[0],xy[1]),e.lineTo(xy[0]+5*Math.cos(a*2*Math.PI/8),xy[1]+5*Math.sin(a*2*Math.PI/8));e.strokeStyle=plot[b].color;e.stroke()}else if(plot[b].flag=="x")for(a=0;a<plot[b].RX.length;a++){e.beginPath();plot_t_highlight[0]==
plot_t_highlight[1]&&plot[b].t[a]>=plot_t_highlight[0]&&plot[b].t[a]<=plot_t_highlight[1]?(e.lineWidth=4,g=8):(e.lineWidth=2,g=5);e.strokeStyle=plot[b].color;xy=get_xy([plot[b].RX[a],plot[b].RY[a],plot[b].RZ[a]],f,d,rotation.g);for(c=0;c<4;c++)e.moveTo(xy[0],xy[1]),e.lineTo(xy[0]+g*Math.cos(Math.PI/4+c*Math.PI/2),xy[1]+g*Math.sin(Math.PI/4+c*Math.PI/2));e.stroke()}else if(plot[b].flag==">")for(a=0;a<plot[b].RX.length;a++){e.beginPath();plot[b].t[a]>=plot_t_highlight[0]&&plot[b].t[a]<=plot_t_highlight[1]?
(e.lineWidth=3,arrow_len=15):(e.lineWidth=1,arrow_len=10);xy=get_xy([plot[b].RX[a],plot[b].RY[a],plot[b].RZ[a]],f,d,rotation.g);vxy=m_x_v3(rotation.g,[plot[b].VX[a],plot[b].VY[a],plot[b].VZ[a]]);vxy[1]*=-1;v=Math.sqrt(vxy[0]*vxy[0]+vxy[1]*vxy[1]);dr=[-arrow_len*vxy[0]/v,-arrow_len*vxy[1]/v];for(c=0;c<2;c++)theta=c==0?-30*o.DEG2RAD:30*o.DEG2RAD,e.moveTo(xy[0],xy[1]),e.lineTo(xy[0]+(dr[0]*Math.cos(theta)-dr[1]*Math.sin(theta)),xy[1]+(dr[0]*Math.sin(theta)+dr[1]*Math.cos(theta)));e.strokeStyle=plot[b].color;
e.stroke()}else{e.beginPath();e.strokeStyle=plot[b].color;e.fillStyle=plot[b].color;highlight=0;highlight_last=-1;e.lineWidth=plot[b].ID>0?2:1;for(a=0;a<plot[b].RX.length;a++)c=plot[b].t[a],xy=get_xy([plot[b].RX[a],plot[b].RY[a],plot[b].RZ[a]],f,d,rotation.g),b==PLOT_SC?(highlight=c>=plot_t_highlight[0]&&c<plot_t_highlight[1],highlight!=highlight_last?(e.lineTo(xy[0],xy[1]),e.stroke(),e.beginPath(),e.lineWidth=highlight?3:1,e.moveTo(xy[0],xy[1])):e.lineTo(xy[0],xy[1]),highlight_last=highlight):a==
0?e.moveTo(xy[0],xy[1]):e.lineTo(xy[0],xy[1]),animation.on&&c<=animation.t&&a+1<plot[b].t.length&&plot[b].t[a+1]>animation.t&&(g=(animation.t-c)/(plot[b].t[a+1]-c),xy2=get_xy([plot[b].RX[a+1],plot[b].RY[a+1],plot[b].RZ[a+1]],f,d,rotation.g),c=xy[0]+g*(xy2[0]-xy[0]),g=xy[1]+g*(xy2[1]-xy[1]),e.stroke(),e.beginPath(),e.arc(c,g,5,0,Math.PI*2,!0),plot[b].ID<0&&(e.lineWidth+=1),e.stroke(),plot[b].ID<0&&(e.lineWidth-=1),e.beginPath(),e.moveTo(xy[0],xy[1]));e.stroke()}}
function get_xy(b,a,c,g){b=m_x_v3(g,b);g=[0,0];g[0]=b[0]*a[0]+c[0];g[1]=b[1]*a[1]+c[1];return g}
function setupStats(b){var a=0,c,g,d="";itin_table={rows:[],color:[],t1:[],t2:[]};idx_bodies=trajs.idx_bodies[b];document.getElementById("results_table").getElementsByTagName("tr");dest_name=bodies.Name[idx_bodies];dest_name[0]=="("&&(dest_name=dest_name.replace("(",""),dest_name=dest_name.replace(")",""));Mission_ID==1?d="Rendezvous mission to ":Mission_ID==2?d="Round-trip rendezvous mission to ":Mission_ID==3?d="Flyby mission to ":Mission_ID==4&&(d="Round-trip flyby mission to ");document.getElementById("tv_title").innerHTML=
d+dest_name;document.getElementById("tv_dest_name").innerHTML=dest_name;d=document.getElementById("tv_sbdb_link");bodies.SPK_ID[idx_bodies]>1E3?(d.href="http://ssd.jpl.nasa.gov/sbdb.cgi?sstr="+bodies.SPK_ID[idx_bodies],d.innerHTML="[Small-Body Database]"):(d.href="http://solarsystem.nasa.gov/planets/profile.cfm?Object="+getBodyName(bodies.SPK_ID[idx_bodies]),d.innerHTML="[Solar Sytem Exploration]");for(d=document.getElementById("tv_dest_tbl");d.rows.length>0;)d.deleteRow(-1);addStatEntry(d,"SPK-ID",
bodies.SPK_ID[idx_bodies]);addStatEntry(d,"Orbit Condition Code",bodies.OCC[idx_bodies]);bodies.Mag[idx_bodies]!=0&&bodies.Mag[idx_bodies]!=100&&addStatEntry(d,"Absolute Magnitude",FormatNum(bodies.Mag[idx_bodies],1));addStatEntry(d,"Size",FormatBodySize(bodies.Dia1[idx_bodies],bodies.Dia2[idx_bodies]));aei=Body_aei(bodies.SPK_ID[idx_bodies],trajs.EarthDep[b]);addStatEntry(d,"Semi-major axis",FormatNum(aei[0]/o.AU,3)+" AU");addStatEntry(d,"Eccentricity",FormatNum(aei[1],3));addStatEntry(d,"Inclination",
FormatNum(aei[2]*o.RAD2DEG,2)+"&deg;");for(var f=document.getElementById("tv_itin");f.rows.length>1;)f.deleteRow(-1);for(var e=segs["id"+trajs.Traj_ID[b]],d=0,a=e[0];a<=e[1];a++)segs.SPK_ID[a]==10?(segs.nodes[a]==NODE_DSM&&addItinearyEntry(f,"DSM",FormatDate(segs.T[a]),FormatDV(segs.DV[a]),"",[segs.T[a],segs.T[a]]),c=get_previous_node(a),g=get_next_node(a+1),addItinearyEntry(f,FormatDurationDash(segs.T[g]-segs.T[c])+" transfer",-1,-1,-1,[segs.T[c],segs.T[g]])):segs.nodes[a]==NODE_DEPARTURE?(notes=
"C3 = "+Math.round(trajs.C3[b]/1E6*10)/10+" km<sup>2</sup>/s<sup>2</sup><br>DLA = "+Math.round(trajs.DLA[b]/Math.PI*180)+"&deg;",addItinearyEntry(f,"Earth Departure",FormatDate(segs.T[a]),FormatDV(segs.DV[a]),notes,[segs.T[a],segs.T[a]])):segs.nodes[a]==NODE_ARRIVAL?segs.SPK_ID[a]==399?addItinearyEntry(f,"Earth reentry",FormatDate(segs.T[a]),FormatDV(segs.DV[a]),FormatDV(getSpeed(a))+" reentry",[segs.T[a],segs.T[a]]):segs.DV[a]!=0?(getGM(segs.SPK_ID[a])>0&&(d=1),addItinearyEntry(f,getBodyName(segs.SPK_ID[a])+
" Arrival",FormatDate(segs.T[a]),FormatDV(segs.DV[a])+(d?"*":""),"",[segs.T[a],segs.T[a]])):addItinearyEntry(f,getBodyName(segs.SPK_ID[a])+" Flyby",FormatDate(segs.T[a]),FormatDV(segs.DV[a]),FormatDV(getSpeed(a))+" relative speed",[segs.T[a],segs.T[a]]):segs.nodes[a]==NODE_FLYBY?(info_str=FormatDV(getSpeed(a))+" relative speed",getGM(segs.SPK_ID[a])&&(radius=getRadius(segs.SPK_ID[a]),flyby_dist=(norm3([segs.RX[a],segs.RY[a],segs.RZ[a]])-radius)/radius,info_str+="<br>"+Math.round(flyby_dist*100)/100+
" radii altitude"),addItinearyEntry(f,getBodyName(segs.SPK_ID[a])+" Flyby",FormatDate(segs.T[a]),FormatDV(segs.DV[a]),info_str,[segs.T[a],segs.T[a]])):segs.nodes[a]==NODE_STAY_ARRIVAL?(getGM(segs.SPK_ID[a])>0&&(d=1),addItinearyEntry(f,getBodyName(segs.SPK_ID[a])+" Arrival",FormatDate(segs.T[a]),FormatDV(segs.DV[a])+(d?"*":""),"",[segs.T[a],segs.T[a]]),addItinearyEntry(f,FormatDurationDash(segs.T[a+1]-segs.T[a])+" stay",-1,-1,-1,[segs.T[a],segs.T[a+1]])):segs.nodes[a]==NODE_STAY_DEPARTURE&&addItinearyEntry(f,
getBodyName(segs.SPK_ID[a])+" Departure",FormatDate(segs.T[a]),FormatDV(segs.DV[a])+(d?"*":""),"",[segs.T[a],segs.T[a]]);addItinearyEntry(f,FormatDurationDash(trajs.DT[b])+" total mission",-1,-1,-1,[NaN,NaN]);row=f.rows[f.rows.length-1];row.insertCell(-1).innerHTML=FormatDV(trajs.DVpi[b])+"<br>"+FormatDV(trajs.DV[b]);row.insertCell(-1).innerHTML="post-injection &Delta;V<br>total &Delta;V";for(b=document.getElementById("tv_traj_tbl");b.rows.length>0;)b.deleteRow(-1);addStatEntry(b,"Solar range:",Math.round(SCdist.sun.min/
o.AU*100)/100+" - "+Math.round(SCdist.sun.max/o.AU*100)/100+" AU");addStatEntry(b,"Earth range:",Math.round(SCdist.earth.min/o.AU*100)/100+" - "+Math.round(SCdist.earth.max/o.AU*100)/100+" AU");if(d)row=b.insertRow(-1),cell=row.insertCell(-1),cell.colSpan="4",cell.innerHTML="<br>* &Delta;V to/from a C3 = 0 km<sup>2</sup>/s<sup>2</sup> local planetary orbit."}function get_next_node(b){for(;segs.nodes[b]==0;)b++;return b}function get_previous_node(b){for(;segs.nodes[b]==0;)b--;return b}
function addStatEntry(b,a,c){b.rows.length==0||b.rows[b.rows.length-1].cells.length>2?b=b.insertRow(-1):(b=b.rows[b.rows.length-1],b.insertCell(-1).innerHTML="&nbsp;&nbsp;&nbsp;");b.insertCell(-1).innerHTML=a;b.insertCell(-1).innerHTML=c}
function addItinearyEntry(b,a,c,g,d,f){var e=b.insertRow(-1);e.style.backgroundColor=b.rows.length%2==0?"#222222":"#000000";if(!isNaN(f[0]))i=itin_table.rows.length,itin_table.rows.push(e),itin_table.color.push(e.style.backgroundColor),itin_table.t1.push(f[0]),itin_table.t2.push(f[1]),e.addEventListener("mouseover",Itin_table_mouseover,!1),e.addEventListener("mouseout",Itin_table_mouseout,!1);b=e.insertCell(0);b.innerHTML=a;g<0?(b.innerHTML="<i>&nbsp;&nbsp;&nbsp;"+b.innerHTML+"</i>",b.colSpan="2"):
(e.insertCell(1).innerHTML=c,e.insertCell(2).innerHTML=g,e.insertCell(3).innerHTML=d)}function Itin_table_mouseover(b){var a,c;for(a=0;a<itin_table.rows.length;a++)if(c=itin_table.rows[a],c==b.currentTarget)break;plot_t_highlight=[itin_table.t1[a],itin_table.t2[a]];plotBuffer()}
function Itin_table_mouseout(b){var a,c;for(a=0;a<itin_table.rows.length;a++)if(c=itin_table.rows[a],c==b.currentTarget)break;c.style.backgroundColor=itin_table.color[a];plot_t_highlight=[NaN,NaN];plotBuffer()}function animation_loop(){animation.t+=animation.tstep;if(animation.t>animation.tend)animation.t=animation.tend-1,animate_pause();plotBuffer()}function animate_start(){animation.t=animation.tstart;plotBuffer()}function animate_end(){animation.t=animation.tend-1;plotBuffer()}
function animate_play(){document.getElementById("btn_play").style.display="none";document.getElementById("btn_pause").style.display="inline";if(animation.t>=animation.tend-1)animation.t=animation.tstart;animation.timer=setInterval(function(){animation_loop()},50)}function animate_pause(){document.getElementById("btn_pause").style.display="none";document.getElementById("btn_play").style.display="inline";clearInterval(animation.timer)}
function animate_step(b){animation.t+=animation.tstep*b;if(animation.t>animation.tend)animation.t=animation.tend;if(animation.t<animation.tstart)animation.t=animation.tstart;plotBuffer()}function animate_stepsize(b){animation.tstep*=1+b*0.2}function rotation_mousedown(b){rotation.mousedown=1;rotation.xy_mousedown=getCursorPosition(b,document.getElementById("tv_canvas"));rotation.x_axis=m_x_v3(rotation.g,[0,0,1]);rotation.y_axis=m_x_v3(rotation.g,[1,0,0]);rotation.g_base=rotation.g}
function rotation_mousemove(b){if(rotation.mousedown)b=getCursorPosition(b,document.getElementById("tv_canvas")),theta1=(b[0]-rotation.xy_mousedown[0])/100,theta2=-(b[1]-rotation.xy_mousedown[1])/100,g1=m3_get_rot(rotation.x_axis,theta1),g2=m3_get_rot(rotation.y_axis,theta2),rotation.g=m_x_m3(g1,rotation.g_base),rotation.g=m_x_m3(g2,rotation.g),plotBuffer()}function rotation_mouseup(){rotation.mousedown=0}
function rotation_dblclick(){rotation.mousedown=0;rotation.g=[[1,0,0],[0,1,0],[0,0,1]];plotBuffer()};
