var graph;function checkform(){document.forms.form1.method=document.getElementsByName("target_list")[0].value.length<1E3?"get":"post";return!0}
function Graph_load(){var a,c,b=document.getElementById("results_graph"),d=b.getContext("2d");graph={origin:[],axis_len:[],x:[],y:[],color:[]};d.fillStyle="#000000";d.fillRect(0,0,b.width,b.height);colorbar_width=100;graph_padding=50;axis_color="#FFFFFF";data_padding=20;tick_length=5;graph.origin[0]=graph_padding;graph.origin[1]=graph_padding;graph.axis_len[0]=b.width-colorbar_width-graph.origin[0]-graph_padding;graph.axis_len[1]=b.height-graph.origin[1]-graph_padding;d.beginPath();d.moveTo(graph.origin[0],
b.height-(graph.origin[1]+graph.axis_len[1]));d.lineTo(graph.origin[0],b.height-graph.origin[1]);d.lineTo(graph.origin[0]+graph.axis_len[0],b.height-graph.origin[1]);d.strokeStyle=axis_color;d.stroke();d.font="12px sans-serif";d.textAlign="center";d.textBaseline="middle";d.fillStyle=axis_color;d.save();d.fillText("Earth departure",graph.origin[0]+graph.axis_len[0]/2,b.height-10);d.rotate(-Math.PI/2);d.fillText("Duration (years)",-(b.height-(graph.origin[1]+graph.axis_len[1]/2)),10);d.restore();d.fillText("Total DV (km/s)",
b.width-colorbar_width/2,b.height-graph_padding+20);colorbar_x=b.width-colorbar_width+10;colorbar_y=graph_padding;colorbar_w=20;colorbar_h=b.height-2*graph_padding;d.strokeStyle=axis_color;d.strokeRect(colorbar_x,colorbar_y,colorbar_w,colorbar_h);for(h=0;h<colorbar_h;h++)d.beginPath(),d.strokeStyle=colormap_jet(h/colorbar_h),d.moveTo(colorbar_x,colorbar_y+colorbar_h-h),d.lineTo(colorbar_x+colorbar_w,colorbar_y+colorbar_h-h),d.stroke();var f=[],g=[];f[0]=Math.min.apply(null,trajs.EarthDep);g[0]=Math.max.apply(null,
trajs.EarthDep);f[1]=Math.min.apply(null,trajs.DT);g[1]=Math.max.apply(null,trajs.DT);f[2]=Math.min.apply(null,trajs.DV);g[2]=Math.max.apply(null,trajs.DV);var e=[],i=[[],[],[]];e[0]=[5*o.day,10*o.day,15*o.day,30*o.day,60*o.day,90*o.day,120*o.day,180*o.day,o.yr,2*o.yr,3*o.yr,5*o.yr];e[1]=[0.05*o.yr,0.1*o.yr,0.2*o.yr,0.25*o.yr,0.5*o.yr,o.yr,2*o.yr,3*o.yr,5*o.yr];e[2]=[100,200,250,500,1E3,2E3,2500,5E3];n_max_labels=[8,6,8];for(a=0;a<3;a++){data_span=g[a]-f[a];for(i_step=0;data_span/e[a][i_step]>n_max_labels[a]&&
i_step<e[a].length-1;)i_step++;if(data_span==0)i[a]=[f[a]];else{a==0?(YMD=J2000_to_YMD(f[a]),e[a][i_step]>=180*o.day&&(YMD[1]=1),tick=YMD_to_J2000(YMD[0],YMD[1],1)):tick=Math.floor(f[a]/e[a][i_step])*e[a][i_step];for(c=1;c<n_max_labels[a]*2;c++){a==0&&(YMD=J2000_to_YMD(tick),YMD[2]>=28&&(tick=YMD_to_J2000(YMD[0],YMD[1]+1,1)),YMD[2]==6&&(tick=YMD_to_J2000(YMD[0],YMD[1],5)));tick+e[a][i_step]>f[a]&&i[a].push(tick);if(tick>g[a])break;tick+=e[a][i_step]}}f[a]=Math.min(f[a],i[a][0]);g[a]=Math.max(g[a],
i[a][i[a].length-1])}c=[];e=[];for(a=0;a<2;a++)f[a]!=g[a]?(c[a]=1/(g[a]-f[a])*(graph.axis_len[a]-2*data_padding),e[a]=-f[a]*c[a]+graph.origin[a]+data_padding):(c[a]=0,e[a]=graph.origin[a]+data_padding+(graph.axis_len[a]-2*data_padding)/2);c[1]*=-1;e[1]=b.height-e[1];f[2]!=g[2]?(c[2]=1/(g[2]-f[2]),e[2]=-f[2]*c[2]):(c[2]=0,e[2]=0.5);d.font="10px sans-serif";d.strokeStyle=axis_color;for(a=0;a<i[0].length;a++)d.beginPath(),d.moveTo(i[0][a]*c[0]+e[0],b.height-graph.origin[1]),d.lineTo(i[0][a]*c[0]+e[0],
b.height-graph.origin[1]+tick_length),d.stroke(),d.fillText(FormatDate(i[0][a]),i[0][a]*c[0]+e[0],b.height-graph.origin[1]+tick_length+10);for(a=0;a<i[1].length;a++)d.beginPath(),d.moveTo(graph.origin[0],i[1][a]*c[1]+e[1]),d.lineTo(graph.origin[0]-tick_length,i[1][a]*c[1]+e[1]),d.stroke(),d.fillText(Math.round(i[1][a]/86400/365.25*100)/100,graph.origin[0]-tick_length-10,i[1][a]*c[1]+e[1]);for(a=0;a<i[2].length;a++)d.beginPath(),d.moveTo(colorbar_x+colorbar_w,colorbar_y+colorbar_h*(1-i[2][a]*c[2]-
e[2])),d.lineTo(colorbar_x+colorbar_w+tick_length,colorbar_y+colorbar_h*(1-i[2][a]*c[2]-e[2])),d.stroke(),d.fillText(Math.round(i[2][a]/1E3*100)/100,colorbar_x+colorbar_w+tick_length+10,colorbar_y+colorbar_h*(1-i[2][a]*c[2]-e[2]));for(a=0;a<trajs.Traj_ID.length;a++)graph.x[a]=trajs.EarthDep[a]*c[0]+e[0],graph.y[a]=trajs.DT[a]*c[1]+e[1],graph.color[a]=colormap_jet(trajs.DV[a]*c[2]+e[2]);graph.r=5;graph.r_mouseover=10;graph.is_mouseover=0;Graph_drawData();b.addEventListener("mousemove",Graph_mousemove,
!1);b.addEventListener("click",Graph_click,!1);b.addEventListener("mouseout",Graph_mouseout,!1)}
function Graph_drawData(){var a=document.getElementById("results_graph"),c=a.getContext("2d");c.fillStyle="#000000";c.fillRect(graph.origin[0],a.height-(graph.origin[1]+graph.axis_len[1]),graph.axis_len[0],graph.axis_len[1]);for(a=0;a<trajs.Traj_ID.length;a++)c.beginPath(),c.fillStyle=graph.color[a],c.strokeStyle=graph.color[a],c.arc(graph.x[a],graph.y[a],graph.r,0,2*Math.PI,!0),c.closePath(),c.fill()}
function Graph_mousemove(a){var c=document.getElementById("results_graph"),b=c.getContext("2d");k=getMouseGraphPoint(a,c);k!=-1?(graph.is_mouseover=1,Graph_drawData(),b.beginPath(),b.fillStyle=graph.color[k],b.strokeStyle=graph.color[k],b.arc(graph.x[k],graph.y[k],graph.r_mouseover,0,2*Math.PI,!0),b.closePath(),b.fill(),c.style.cursor="pointer",Table_show_only_row(trajs.Traj_ID[k])):graph.is_mouseover&&Graph_mouseout(a)}
function Graph_mouseout(){var a=document.getElementById("results_graph");graph.is_mouseover=0;Graph_drawData();a.style.cursor="auto";Table_show_all_rows()}function Graph_click(a){k=getMouseGraphPoint(a,document.getElementById("results_graph"));k!=-1&&TrajViewer_open(trajs.Traj_ID[k])}
function getMouseGraphPoint(a,c){for(var b=[],d=[],f=getCursorPosition(a,c),g=0;g<trajs.Traj_ID.length;g++)offset=sqrt(sq(f[0]-graph.x[g])+sq(f[1]-graph.y[g])),offset<graph.r_mouseover&&(b.push(g),d.push(offset));if(b.length==0)return-1;else if(b.length==1)return b[0];else{f=min(d);for(g=0;g<d.length;g++)if(d[g]==f)return b[g]}}
function getCursorPosition(a,c){var b=[];a.pageX||a.pageY?b=[a.pageX,a.pageY]:(b[0]=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,b[1]=a.clientY+document.body.scrollTop+document.documentElement.scrollTop);b[0]-=c.offsetLeft;b[1]-=c.offsetTop+30;return b}
function Table_load(){var a=document.getElementById("results_table"),c=0,b=0;for(k=0;k<trajs.Traj_ID.length;k++)j=trajs.idx_bodies[k],c=a.insertRow(-1),c.id="tr_"+trajs.Traj_ID[k],c.insertCell(-1).innerHTML='<button onClick="TrajViewer_open('+trajs.Traj_ID[k]+')">View</button>',c.insertCell(-1).innerHTML=trajs.SPK_ID[k],c.insertCell(-1).innerHTML=bodies.Name[j],b=c.insertCell(-1),b.innerHTML=FormatMag(bodies.Mag[j]),b.setAttribute("sorttable_customkey",bodies.Mag[j]?bodies.Mag[j]:0),b=c.insertCell(-1),
b.innerHTML=FormatBodySize(bodies.Dia1[j],bodies.Dia2[j]),b.setAttribute("sorttable_customkey",bodies.Dia2[j]?bodies.Dia2[j]:1E10),c.insertCell(-1).innerHTML=bodies.OCC[j],b=c.insertCell(-1),b.innerHTML=FormatDate(trajs.EarthDep[k]),b.setAttribute("sorttable_customkey",trajs.EarthDep[k]),b=c.insertCell(-1),b.innerHTML=FormatDate(trajs.DestArr[k]),b.setAttribute("sorttable_customkey",trajs.DestArr[k]),b=c.insertCell(-1),b.innerHTML=FormatDate(trajs.DestFlyby[k]),b.setAttribute("sorttable_customkey",
trajs.DestFlyby[k]),b=c.insertCell(-1),b.innerHTML=FormatDate(trajs.DestDep[k]),b.setAttribute("sorttable_customkey",trajs.DestDep[k]),b=c.insertCell(-1),b.innerHTML=FormatDate(trajs.EarthArr[k]),b.setAttribute("sorttable_customkey",trajs.EarthArr[k]),b=c.insertCell(-1),b.innerHTML=FormatDuration(trajs.DTdest[k]),b.setAttribute("sorttable_customkey",trajs.DTdest[k]),b=c.insertCell(-1),b.innerHTML=FormatDuration(trajs.DT[k]),b.setAttribute("sorttable_customkey",trajs.DT[k]),c.insertCell(-1).innerHTML=
Math.round(trajs.C3[k]/1E6*10)/10,b=c.insertCell(-1),b.innerHTML=Math.round(Math.abs(trajs.DLA[k])/Math.PI*180)+"&deg;",b.setAttribute("sorttable_customkey",Math.abs(trajs.DLA[k])),c.insertCell(-1).innerHTML=Math.round(trajs.DVi[k]/1E3*100)/100,c.insertCell(-1).innerHTML=Math.round(trajs.DVpi[k]/1E3*100)/100,c.insertCell(-1).innerHTML=Math.round(trajs.DV[k]/1E3*100)/100,c.insertCell(-1).innerHTML=Math.round(trajs.Vflyby[k]/1E3*100)/100,c.insertCell(-1).innerHTML=Math.round(trajs.Vreentry[k]/1E3*100)/
100,c.insertCell(-1).innerHTML=trajs.Route[k];a=[];Mission_ID==1?a="DestFlyby,DestDep,EarthArr,DTdest,Vflyby,Vreentry".split(","):Mission_ID==3?a=["DestArr","DestDep","EarthArr","DTdest","Vreentry"]:Mission_ID==2?a=["DestFlyby","Vflyby"]:Mission_ID==4&&(a=["DestArr","DestDep","DTdest"]);for(k=0;k<a.length;k++)Table_set_column_visiblity(a[k],0),Table_set_checkbox_visiblity(a[k],0);Table_color()}
function Table_set_column_visiblity(a,c){for(var b=document.getElementById("results_table"),d=document.getElementById("th_"+a).cellIndex,f=0;f<b.rows.length;f++)b.rows[f].cells[d].style.display=c?"":"none"}function Table_checkbox_toggle(a){Table_set_column_visiblity(a,document.getElementById("chk_"+a).checked)}
function Table_check_all_cols(a){tbl=document.getElementById("tbl_cols");for(var c=0;c<tbl.rows.length;c++)if((field=tbl.rows[c].id.substr(3))&&document.getElementById("tr_"+field).style.display!="none")document.getElementById("chk_"+field).checked=a,Table_checkbox_toggle(field)}function Table_set_checkbox_visiblity(a,c){document.getElementById("tr_"+a).style.display=c?"":"none"}
function Table_set_checkboxes_visibility(a){document.getElementById("img_cols_closed").style.display=!a?"":"none";document.getElementById("img_cols_opened").style.display=a?"":"none";document.getElementById("tbl_cols").style.display=a?"":"none"}function Table_show_only_row(a){for(var c=document.getElementById("results_table"),b=1;b<c.rows.length;b++)c.rows[b].style.display=c.rows[b].id.substr(3)==a?"":"none";Table_color()}
function Table_show_all_rows(){for(var a=document.getElementById("results_table"),c=1;c<a.rows.length;c++)a.rows[c].style.display="";Table_color()}function Table_color(){for(var a=document.getElementById("results_table"),c=0,b=0;b<a.rows.length;b++)if(a.rows[b].style.display=="")a.rows[b].style.backgroundColor=c++%2?"#000000":"#222222",a.rows[b].cells[0].style.backgroundColor="#000000"}
function Table_exportCSV(){for(var a=document.getElementById("results_table"),c=[],b=0;b<a.rows[0].cells.length;b++)a.rows[0].cells[b].style.display!="none"&&c.push(a.rows[0].cells[b].id.substr(3));b="CSV:";contains(c,"SPK_ID")&&(b+="SPK-ID,");contains(c,"Name")&&(b+="Name,");contains(c,"Mag")&&(b+="Abs_Mag,");contains(c,"Size")&&(b+="Size,");contains(c,"OCC")&&(b+="Orbit_Condition_Code,");contains(c,"EarthDep")&&(b+="Earth_Departure,");contains(c,"DestArr")&&(b+="Dest_Arrival,");contains(c,"DestFlyby")&&
(b+="Dest_Flyby,");contains(c,"DestDep")&&(b+="Dest_Departure,");contains(c,"EarthArr")&&(b+="Earth_Return,");contains(c,"DTdest")&&(b+='"Stay time (days)",');contains(c,"DT")&&(b+='"Duration (days)",');contains(c,"C3")&&(b+='"C3 (km2/s2)",');contains(c,"DLA")&&(b+='"Abs DLA (degs)",');contains(c,"DVi")&&(b+='"Injection DV (km/s)",');contains(c,"DVpi")&&(b+='"Post-injection DV (km/s)",');contains(c,"DV")&&(b+='"Total DV (km/s)",');contains(c,"Vflyby")&&(b+='"Flyby speed (km/s)",');contains(c,"Vreentry")&&
(b+='"Reentry speed (km/s)",');contains(c,"Route")&&(b+="Route,");for(var d=1;d<a.rows.length;d++)c.length!=0&&(b+="\r\n",Traj_ID=a.rows[d].id.substr(3),k=trajs["id"+Traj_ID],j=trajs.idx_bodies[k],contains(c,"SPK_ID")&&(b+=trajs.SPK_ID[k]+","),contains(c,"Name")&&(b+='"'+bodies.Name[j]+'",'),contains(c,"Mag")&&(b+=FormatMag(bodies.Mag[j])+","),contains(c,"Size")&&(b+='"'+FormatBodySize(bodies.Dia1[j],bodies.Dia2[j])+'",'),contains(c,"OCC")&&(b+=bodies.OCC[j]+","),contains(c,"EarthDep")&&(b+=FormatDate(trajs.EarthDep[k])+
","),contains(c,"DestArr")&&(b+=FormatDate(trajs.DestArr[k])+","),contains(c,"DestFlyby")&&(b+=FormatDate(trajs.DestFlyby[k])+","),contains(c,"DestDep")&&(b+=FormatDate(trajs.DestDep[k])+","),contains(c,"EarthArr")&&(b+=FormatDate(trajs.EarthArr[k])+","),contains(c,"DTdest")&&(b+=FormatNum(trajs.DTdest[k]/o.day,0)+","),contains(c,"DT")&&(b+=FormatNum(trajs.DT[k]/o.day,0)+","),contains(c,"C3")&&(b+=Math.round(trajs.C3[k]/1E6*10)/10+","),contains(c,"DLA")&&(b+=Math.round(Math.abs(trajs.DLA[k])/Math.PI*
180)+","),contains(c,"DVi")&&(b+=Math.round(trajs.DVi[k]/1E3*100)/100+","),contains(c,"DVpi")&&(b+=Math.round(trajs.DVpi[k]/1E3*100)/100+","),contains(c,"DV")&&(b+=Math.round(trajs.DV[k]/1E3*100)/100+","),contains(c,"Vflyby")&&(b+=Math.round(trajs.Vflyby[k]/1E3*100)/100+","),contains(c,"Vreentry")&&(b+=Math.round(trajs.Vreentry[k]/1E3*100)/100+","),contains(c,"Route")&&(b+=trajs.Route[k]+","));a=document.createElement("form");a.method="POST";a.action="php/echo_csv.php";c=document.createElement("input");
c.setAttribute("type","hidden");c.setAttribute("name","data");c.setAttribute("value",b);a.appendChild(c);document.body.appendChild(a);a.submit();document.body.removeChild(a)};
