var o=[];o.AU=149598E6;o.day=86400;o.yr=31557600;o.DEG2RAD=0.017453292519943;o.RAD2DEG=57.29577951308232;o.months="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(",");var ID_SUN=10,ID_EARTH=399,ID_VENUS=299,ID_MARS=499,NODE_DSM=1,NODE_DEPARTURE=2,NODE_ARRIVAL=3,NODE_FLYBY=4,NODE_STAY_ARRIVAL=5,NODE_STAY_DEPARTURE=6;function sign(b){return b==0?0:b>0?1:-1}function sin(b){return Math.sin(b)}function cos(b){return Math.cos(b)}function sinh(b){return(Math.exp(b)-Math.exp(-b))/2}
function cosh(b){return(Math.exp(b)+Math.exp(-b))/2}function sq(b){return b*b}function fabs(b){return Math.abs(b)}function log(b){return Math.log(b)}function sqrt(b){return Math.sqrt(b)}function floor(b){return Math.floor(b)}function dec2hex_2(b){return(b<16?"0":"")+b.toString(16)}function cross3(b,c){return[b[1]*c[2]-b[2]*c[1],b[2]*c[0]-b[0]*c[2],b[0]*c[1]-b[1]*c[0]]}function norm3(b){return Math.sqrt(b[0]*b[0]+b[1]*b[1]+b[2]*b[2])}
function contains(b,c){for(var d=b.length;d--;)if(b[d]==c)return 1;return 0}function min(b){return Math.min.apply(null,b)}function max(b){return Math.max.apply(null,b)}
function colormap_jet(b){return b<0.125?"#0000"+dec2hex_2(Math.round(255*(b+0.125)/0.25)):b<0.375?"#00"+dec2hex_2(Math.round(255*(b-0.125)/0.25))+"FF":b<0.625?"#"+dec2hex_2(Math.round(255*(b-0.375)/0.25))+"FF"+dec2hex_2(Math.round(255*(0.625-b)/0.25)):b<0.875?"#FF"+dec2hex_2(Math.round(255*(0.875-b)/0.25))+"00":"#"+dec2hex_2(Math.round(255*(1.125-b)/0.25))+"0000"}
function YMD_to_J2000(b,c,d){var g;arguments.length==1&&(d=b[2],c=b[1],b=b[0]);g=b<=1585?0:1;return(-Math.floor(7*(Math.floor((c+9)/12)+b)/4)+Math.floor(275*c/9)+d-g*Math.floor((Math.floor(Math.floor(b+(c<9?-1:1)*Math.floor(Math.abs(c-9)/7))/100)+1)*3/4)+1721027+2*g+367*b-2451545.5)*86400}
function J2000_to_YMD(b){var c,d,g,l,j,n=[],b=Math.floor(b/86400+2451545.5)+32044;c=b%146097;d=Math.floor((Math.floor(c/36524)+1)*3/4);c-=d*36524;g=c%1461;l=Math.floor((Math.floor(g/365)+1)*3/4);g-=l*365;j=Math.floor((g*5+308)/153)-2;n[0]=Math.floor(b/146097)*400+d*100+Math.floor(c/1461)*4+l-4800+Math.floor((j+2)/12);n[1]=(j+2)%12+1;n[2]=g-Math.floor((j+4)*153/5)+123;return n}
function m3_get_rot(b,c){var d,g,l=[[0,0,0],[0,0,0],[0,0,0]];d=cos(c);g=sin(c);l[0][0]=d+b[0]*b[0]*(1-d);l[0][1]=b[0]*b[1]*(1-d)-b[2]*g;l[0][2]=b[0]*b[2]*(1-d)+b[1]*g;l[1][0]=b[1]*b[0]*(1-d)+b[2]*g;l[1][1]=d+b[1]*b[1]*(1-d);l[1][2]=b[1]*b[2]*(1-d)-b[0]*g;l[2][0]=b[2]*b[0]*(1-d)-b[1]*g;l[2][1]=b[2]*b[1]*(1-d)+b[0]*g;l[2][2]=d+b[2]*b[2]*(1-d);return l}
function m_x_v3(b,c){var d=[0,0,0];d[0]=b[0][0]*c[0]+b[0][1]*c[1]+b[0][2]*c[2];d[1]=b[1][0]*c[0]+b[1][1]*c[1]+b[1][2]*c[2];d[2]=b[2][0]*c[0]+b[2][1]*c[1]+b[2][2]*c[2];return d}function m_x_m3(b,c){var d=[[0,0,0],[0,0,0],[0,0,0]],g,l;for(g=0;g<3;g++)for(l=0;l<3;l++)d[g][l]=b[g][0]*c[0][l]+b[g][1]*c[1][l]+b[g][2]*c[2][l];return d}function FormatNum(b,c){return Math.round(b*Math.pow(10,c))/Math.pow(10,c)}
function FormatDate(b){YMD=J2000_to_YMD(b);return o.months[YMD[1]-1]+"-"+(YMD[2]<10?"0"+YMD[2]:YMD[2])+"-"+YMD[0]}function FormatDuration(b){return b>31557600?Math.round(b/86400/365.25*100)/100+" yrs":Math.round(b/86400)+" days"}function FormatDurationDash(b){return b>31557600?Math.round(b/86400/365.25*100)/100+"-yr":Math.round(b/86400)+"-day"}function FormatDV(b){return b<1?"-":b<1E3?Math.round(b)+" m/s":Math.round(b/1E3*100)/100+" km/s"}
function FormatBodySize(b,c){return b==0?"":b==c?b>1E3?Math.round(b/1E3)+" km":Math.round(b)+" m":b>1E3?Math.round(b/1E3)+"-"+Math.round(c/1E3)+" km":Math.round(b)+"-"+Math.round(c)+" m"}function FormatMag(b){return b=="0"||b=="100"?"":Math.round(b*10)/10}function getObjectColor(b){return b==10?"#FFFF00":b==-1?"#00FF00":b==399?"#4444FF":b==299?"#FF00FF":b==499?"#FF0000":b==5?"#FF8800":b==6?"#BBBB00":b==7?"#9999FF":b==8?"#BBBBFF":b==199?"#999999":"#808080"}
function getGM(b){var c;for(c=0;c<bodies.SPK_ID.length;c++)if(b==bodies.SPK_ID[c])return bodies.GM[c];return 0}function getRadius(b){var c;for(c=0;c<bodies.SPK_ID.length;c++)if(b==bodies.SPK_ID[c])return(bodies.Dia1[c]+bodies.Dia2[c])/4;return 0}function getBodyName(b){if(b>=2E6)return"Asteroid";else if(b>=1E6)return"Comet";else{var c;for(c=0;c<bodies.SPK_ID.length;c++)if(b==bodies.SPK_ID[c])return bodies.Name[c];return"??"}}function getCommonParent(){return 10}
function getParentBody(b){return b==301?399:10}function get_segs_r(b){return Math.sqrt(sq(segs.RX[b])+sq(segs.RY[b])+sq(segs.RZ[b]))}function getSpeed(b){return Math.sqrt(sq(segs.VX[b])+sq(segs.VY[b])+sq(segs.VZ[b]))}function Body_aei(b,c){var d=getParentBody(b),g=getGM(d),d=PropNaturalBody(b,d,c);R=[d[0],d[1],d[2]];V=[d[3],d[4],d[5]];r=norm3(R);v=norm3(V);ey=v*v/2-g/r;H=cross3(R,V);h=norm3(H);a=1/(2/r-v*v/g);e=Math.sqrt(1+2*ey*sq(h)/sq(g));i=Math.acos(H[2]/h);return[a,e,i]}
function Body_sma(b,c){r=Math.sqrt(sq(ephems.RX[c])+sq(ephems.RY[c])+sq(ephems.RZ[c]));v=Math.sqrt(sq(ephems.VX[c])+sq(ephems.VY[c])+sq(ephems.VZ[c]));return 1/(2/r-v*v/b)}function Body_period(b){GM=getGM(getParentBody(b));a=Body_sma(GM,ephems["id"+b][0]);return 2*Math.PI*Math.sqrt(a*a*a/GM)}
function isAllHyperbolic(b,c){var d=0,g=0,l=d=0;for(k=b;k<=c;k++)if(d=Math.sqrt(segs.RX[k]*segs.RX[k]+segs.RY[k]*segs.RY[k]+segs.RZ[k]*segs.RZ[k]),g=Math.sqrt(segs.VX[k]*segs.VX[k]+segs.VY[k]*segs.VY[k]+segs.VZ[k]*segs.VZ[k]),l=getGM(segs.SPK_ID[k]),l==0&&(l=1),d=1/(2/d-g*g/l),d>=0)return 0;return 1}
function PropNaturalBody(b,c,d){var g=[],l=[],l=[0,0],j,n,f;if(b==c)return[0,0,0,0,0,0];else if(b==10){g=PropNaturalBody(c,b,d);for(j=0;j<6;j++)g[j]=-g[j];return g}f=getParentBody(b);l=ephems["id"+b];for(j=l[1];ephems.T[j]>d&&j>l[0];)j--;g=Prop2B(getGM(f),[ephems.RX[j],ephems.RY[j],ephems.RZ[j],ephems.VX[j],ephems.VY[j],ephems.VZ[j]],d-ephems.T[j]);if(d>ephems.T[l[0]]&&d<ephems.T[l[1]]){l=Prop2B(getGM(f),[ephems.RX[j+1],ephems.RY[j+1],ephems.RZ[j+1],ephems.VX[j+1],ephems.VY[j+1],ephems.VZ[j+1]],d-
ephems.T[j+1]);n=0.5+0.5*Math.cos(Math.PI*(d-ephems.T[j])/(ephems.T[j+1]-ephems.T[j]));for(j=0;j<6;j++)g[j]=n*g[j]+(1-n)*l[j]}if(f!=c){baseID=getCommonParent(b,c);s_obs=PropNaturalBody(c,baseID,d);s_prt=PropNaturalBody(f,baseID,d);for(j=0;j<6;j++)g[j]+=s_prt[j]-s_obs[j]}return g}
function Prop2B(b,c,d){var g,l,j,n,f,p,s,m,t,u;m=[];var w,q=[];if(b==0||d==0)return c;l=sqrt(c[0]*c[0]+c[1]*c[1]+c[2]*c[2]);j=sqrt(c[3]*c[3]+c[4]*c[4]+c[5]*c[5]);n=c[0]*c[3]+c[1]*c[4]+c[2]*c[5];alpha=2/l-j*j/b;f=1/alpha;w=10*sqrt(b);f=alpha>=0?sqrt(b)*d*alpha:sign(d)*sqrt(-f)*log(-2*b*d*alpha/(n+sign(d)*sqrt(-b*f)*(1-l*alpha)));for(g=0;g<100;g++){m=Stumpffs_c0123(f*f*alpha);p=f*f*f*m[3]+n*f*f*m[2]/sqrt(b)+l*f*m[1]-sqrt(b)*d;if(fabs(p)<w)break;s=f*f*m[2]+n/sqrt(b)*f*m[1]+l*m[0];f-=p/s}if(g>=100){e1=
j*j-b/l;e=sqrt(sq(e1*c[0]-n*c[3])+sq(e1*c[1]-n*c[4])+sq(e1*c[2]-n*c[5]))/b;f=d*sqrt(b)*alpha/(1-e);m=Stumpffs_c0123(f*f*alpha);u=f*f*f*m[3]+n*f*f*m[2]/sqrt(b)+l*f*m[1]-sqrt(b)*d;s=f;for(g=0;g<100;g++){f*=0.1;m=Stumpffs_c0123(f*f*alpha);p=f*f*f*m[3]+n*f*f*m[2]/sqrt(b)+l*f*m[1]-sqrt(b)*d;if(p*sign(d)<0)break;s=f;u=p}j=0;for(t=-sqrt(b)*d;g<100;g++)if(f=(j+s)*0.5,m=Stumpffs_c0123(f*f*alpha),p=f*f*f*m[3]+n*f*f*m[2]/sqrt(b)+l*f*m[1]-sqrt(b)*d,sign(t)==sign(p)?(j=f,t=p):(s=f,u=p),fabs(t-u)<w)break}if(g>=
100)return 0;p=1-f*f/l*m[2];n=d-f*f*f/sqrt(b)*m[3];for(d=0;d<3;d++)q[d]=p*c[d]+n*c[d+3];p=Math.sqrt(q[0]*q[0]+q[1]*q[1]+q[2]*q[2]);b=-Math.sqrt(b)/(l*p)*f*m[1];m=1-f*f/p*m[2];for(d=3;d<6;d++)q[d]=b*c[d-3]+m*c[d];return q}
function Stumpffs_c0123(b){var c=[0,0,0,0];b>0.01?(sqrt_z=sqrt(b),c[0]=cos(sqrt_z),c[1]=sin(sqrt_z)/sqrt_z,c[2]=(1-c[0])/b,c[3]=(1-c[1])/b):b<-0.01?(sqrt_z=sqrt(-b),c[0]=cosh(sqrt_z),c[1]=sinh(sqrt_z)/sqrt_z,c[2]=(1-c[0])/b,c[3]=(1-c[1])/b):(c[0]=b>=0?cos(sqrt(b)):cosh(sqrt(-b)),c[1]=1-b/6+b*b/120-b*b*b/5040,c[2]=0.5-b/24+b*b/720,c[3]=1/6-b/120+b*b/5040);return c}
function mark_nodes(){var b,c,d,g;segs.nodes=[];for(c=0;c<segs.Traj_ID.length;c++)segs.nodes[c]=0;for(g=0;g<trajs.Traj_ID.length;g++){b=segs["id"+trajs.Traj_ID[g]];for(c=b[0];c<=b[1];c++)if(segs.SPK_ID[c]==10)segs.DV[c]>1&&(segs.nodes[c]=NODE_DSM);else{for(d=c;d<b[1]&&segs.SPK_ID[c]==segs.SPK_ID[d+1];)d++;c==b[0]?segs.nodes[c]=NODE_DEPARTURE:d==b[1]?segs.nodes[d]=NODE_ARRIVAL:isAllHyperbolic(c,d)?segs.nodes[d]=NODE_FLYBY:(segs.nodes[d-1]=NODE_STAY_ARRIVAL,segs.nodes[d]=NODE_STAY_DEPARTURE);c=d}}}
function index_ephems(){var b=ephems.SPK_ID[0];ephems["id"+b]=[0,0];for(var c=0;c<ephems.SPK_ID.length;c++)b!=ephems.SPK_ID[c]&&(ephems["id"+b][1]=c-1,b=ephems.SPK_ID[c],ephems["id"+b]=[c,0]);ephems["id"+b][1]=c-1}
function index_segs(){var b=segs.Traj_ID[0];segs["id"+b]=[0,0];for(var c=0;c<segs.Traj_ID.length;c++)b!=segs.Traj_ID[c]&&(segs["id"+b][1]=c-1,b=segs.Traj_ID[c],segs["id"+b]=[c,0]);segs["id"+b][1]=c-1}
function load_trajs(){var b,c;trajs.EarthDep=[];trajs.DestArr=[];trajs.DestFlyby=[];trajs.DestDep=[];trajs.EarthArr=[];trajs.DT=[];trajs.DTdest=[];trajs.C3=[];trajs.DLA=[];trajs.DVi=[];trajs.DVpi=[];trajs.Vflyby=[];trajs.Vreentry=[];trajs.DV=[];trajs.Route=[];trajs.idx_bodies=[];var d=[];for(c=0;c<trajs.Traj_ID.length;c++){d=segs["id"+trajs.Traj_ID[c]];trajs.Route[c]="";for(b=d[0];b<=d[1];b++)segs.SPK_ID[b]!=10&&(segs.nodes[b]==NODE_DEPARTURE?(trajs.EarthDep[c]=segs.T[b],trajs.C3[c]=sq(segs.VX[b])+
sq(segs.VY[b])+sq(segs.VZ[b])-2*getGM(ID_EARTH)/Math.sqrt(sq(segs.RX[b])+sq(segs.RY[b])+sq(segs.RZ[b])),trajs.DLA[c]=Math.asin((segs.VY[b]*Math.sin(0.40909)+segs.VZ[b]*Math.cos(0.40909))/Math.sqrt(sq(segs.VX[b])+sq(segs.VY[b])+sq(segs.VZ[b]))),trajs.DVi[c]=segs.DV[b],trajs.Route[c]+=getBodyName(segs.SPK_ID[b])[0]):segs.nodes[b]==NODE_ARRIVAL?(segs.SPK_ID[b]==ID_EARTH?(trajs.Vreentry[c]=Math.sqrt(sq(segs.VX[b])+sq(segs.VY[b])+sq(segs.VZ[b])),trajs.EarthArr[c]=segs.T[b]):segs.DV[b]!=0?trajs.DestArr[c]=
segs.T[b]:(trajs.DestFlyby[c]=segs.T[b],trajs.Vflyby[c]=Math.sqrt(sq(segs.VX[b])+sq(segs.VY[b])+sq(segs.VZ[b]))),trajs.Route[c]+=getBodyName(segs.SPK_ID[b])[0]):segs.nodes[b]==NODE_FLYBY?(segs.SPK_ID[b]==trajs.SPK_ID[c]&&(trajs.DestFlyby[c]=segs.T[b],trajs.Vflyby[c]=Math.sqrt(sq(segs.VX[b])+sq(segs.VY[b])+sq(segs.VZ[b]))),trajs.Route[c]+=getBodyName(segs.SPK_ID[b])[0]):segs.nodes[b]==NODE_STAY_ARRIVAL&&(trajs.DestArr[c]=segs.T[b],trajs.DestDep[c]=segs.T[b+1],trajs.DTdest[c]=trajs.DestDep[c]-trajs.DestArr[c],
trajs.Route[c]+=getBodyName(segs.SPK_ID[b])[0]+"-"+getBodyName(segs.SPK_ID[b])[0]));trajs.DT[c]=segs.T[d[1]]-segs.T[d[0]];trajs.DV[c]=0;for(b=d[0];b<=d[1];b++)trajs.DV[c]+=segs.DV[b];trajs.DVpi[c]=trajs.DV[c]-trajs.DVi[c];trajs["id"+trajs.Traj_ID[c]]=c;for(b=0;b<bodies.SPK_ID.length&&bodies.SPK_ID[b]!=trajs.SPK_ID[c];)b++;trajs.idx_bodies[c]=b}};
